---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
    - npm install -g yarn
script:
  - yarn install  
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - yarn ci
        - npx expo login -u heisdeku -p Ayanfeoluwa21+
        - npx expo publish --non-interactive
        - npx expo build:android