---
language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
    - .jest
before_script:    
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.22.10
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn install    
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:        
        - npx expo login -u heisdeku -p Ayanfeoluwa21+
        - npx expo publish --non-interactive
        - travis_wait npx expo build:android -t apk
        - travis_wait npx expo build:android -t app-bundle
