export const DownloadTypes = {
    CLEAR_DOWNLOADS: 'CLEAR_DOWNLOADS',
    SET_DOWNLOAD: 'SET_DOWNLOAD',
    SET_DOWNLOAD_ERROR: 'SET_DOWNLOAD_ERROR',
    START_DOWNLOAD_LOADING: 'START_DOWNLOAD_LOADING',
    END_DOWNLOAD_LOADING: 'END_DOWNLOAD_LOADING',
    DELETE_DOWNLOAD: 'DELETE_DOWNLOAD'
}