export const feedTypes = {
    FETCH_LATEST_START: 'FETCH_LATEST_START',
    FETCH_LATEST_SUCCESS: 'FETCH_LATEST_SUCCESS',
    FETCH_LATEST_FAILED: 'FETCH_LATEST_FAILED',
    FETCH_ALLNEWS_START: 'FETCH_ALNEWS_START',
    FETCH_ALLNEWS_SUCCESS: 'FETCH_ALLNEWS_SUCCESS',
    FETCH_ALLNEWS_FAILED: 'FETCH_ALLNEWS_FAILED',
    FETCH_TRENDING_START: 'FETCH_TRENDING_START',
    FETCH_TRENDING_SUCCESS: 'FETCH_TRENDING_SUCCESS',
    FETCH_TRENDING_FAILED: 'FETCH_TRENDING_FAILED',
    FETCH_TOPNEWS_START: 'FETCH_TOPNEWS_START',
    FETCH_TOPNEWS_SUCCESS: 'FETCH_TOPNEWS_SUCCESS',
    FETCH_TOPNEWS_FAILED: 'FETCH_TOPNEWS_FAILED',
  }