export const InterestActionTypes = {
    START_INTEREST_LOADING: 'START_INTEREST_LOADING',
    END_INTEREST_LOADING: 'END_INTEREST_LOADING',
    SET_INTERESTS: 'SET_INTERESTS',
    SET_INTEREST_ERROR: 'SET_INTEREST_ERROR'
}