export const mediaTypes = {
    FETCH_DOCUMENTARIES_START: 'FETCH_DOCUMENTARIES_START',
    FETCH_DOCUMENTARIES_SUCCESS: 'FETCH_DOCUMENTARIES_SUCCESS',
    FETCH_DOCUMENTARIES_FAILED: 'FETCH_DOCUMENTARIES_FAILED',
    FETCH_GLANCE_START: 'FETCH_GLANCE_START',
    FETCH_GLANCE_SUCCESS: 'FETCH_GLANCE_SUCCESS',
    FETCH_GLANCE_FAILED: 'FETCH_GLANCE_FAILED',
    SET_FOCUS: 'SET_FOCUS',
  }