export const newsTypes = {
    FETCH_NEWS_START: 'FETCH_NEWS_START',
    FETCH_NEWS: 'FETCH_NEWS',
    FETCH_NEWS_FAILED: 'FETCH_NEWS_FAILED',
    GET_COMMENTS: 'GET_COMMENTS',
    ADD_COMMENT: 'ADD_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    CLEAR_NEWS: 'CLEAR_NEWS'
}