export const NewsCategoriesTypes = {
    START_CATEGORIES_LOADING: 'START_CATEGORIES_LOADING',
    END_CATEGORIES_LOADING: 'END_CATEGORIES_LOADING',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_CATEGORIES_ERROR: 'SET_CATEGORIES_ERROR'
}