export const notificationTypes = {    
    SET_PUSH_TOKEN: 'SET_PUSH_TOKEN',
    SET_ALL_NOTIFICATION: 'SET_ALL_NOTIFICATIONS',
    SET_TOPNEWS_NOTIFICATIONS: 'SET_TOP_NEWS_NOTIFICATIONS',
    REMOVE_TOPNEWS_NOTIFICATIONS: 'REMOVE_TOPNEWS_NOTIFICATIONS',
    SET_RECOMMENDATIONS_NOTIFICATIONS: 'SET_RECOMMENDATIONS_NOTIFICATIONS',
    REMOVE_RECOMMENDATIONS_NOTIFICATIONS: 'REMOVE_RECOMMENDATIONS_NOTIFICATIONS',
    SET_PRODUCTS_NOTIFICATIONS: 'SET_PRODUCTS_NOTIFICATIONS',
    REMOVE_PRODUCTS_NOTIFICATIONS: 'REMOVE_PRODUCTS_NOTIFICATIONS',
}