//search constants
export const searchTypes = {
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    GET_SEARCH_VALUE: 'GET_SEARCH_VALUE',
    SEARCH_VALUE_START: 'SEARCH_VALUE_START',
    SEARCH_VALUE_SUCCESS: 'SEARCH_VALUE_SUCCESS',
    SEARCH_VALUE_FAILED: 'SEARCH_VALUE_FAILED',
    SEARCH_VALUE_BY_CATEGORY_START: 'SEARCH_VALUE_BY_CATEGORY_START',
    SEARCH_VALUE_BY_CATEGORY_SUCCESS: 'SEARCH_VALUE_BY_CATEGORY_SUCCESS',
    SEARCH_VALUE_BY_CATEGORY_FAILED: 'SEARCH_VALUE_BY_CATEGORY_FAILED',
  }
  