//user constants
export const userTypes = {
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    FACEBOOK_SIGN_IN_START: 'FACEBOOK_SIGN_IN_START',
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    SIGN_UP_START: 'SIGN_UP_START',
    LOGOUT_USER: 'LOGOUT_USER',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    CLEAR_SOCIAL_USER: 'CLEAR_SOCIAL_USER',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    SET_USER_START: 'SET_USER_START',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_FAILED: 'SET_USER_FAILED',
  }