import React from 'react';
import { StyleSheet, Text, ScrollView, View, ImageBackground, Dimensions } from 'react-native';
import { Feather, MaterialIcons, AntDesign, FontAwesome5  } from '@expo/vector-icons';
import Colors from '../../colors/colors';

const ArticleRead = ({navigation, route}) => {
    console.log(route)
    return (
        <ScrollView style={styles.news}>
            <View style={styles.imageContainer}>
                <ImageBackground source={require('../../../assets/images/dummy-article-image.png')} style={styles.image} />
            </View>
            <View style={styles.articleCategoryContainer}>
                <Text style={styles.articleCategoryText}>Business</Text>
                <AntDesign name="right" size={12} color="black" />
                <Text style={styles.articleCategoryText}>Features</Text>
            </View>
            <View style={styles.newsDetails}>
                <View style={styles.crumbs}>
                    <View>
                        <Text style={styles.newsTitle}>How Qatar became the richest country in the world</Text>
                        <Text style={styles.newsCaption}>Qatar, By far, the richest country in the world, with a GNI per capita of $116,799 — more than $20,000 higher than any other nation in the world.</Text>
                    </View>                    
                    <View style={styles.newsSummary}>
                        <View style={styles.newsSummaryItem}>
                            <Feather size={14} color={Colors.text1} name='clock' />
                            <Text style={styles.newsSummaryText}> Oct 27, 2020</Text>
                        </View>
                        <View style={styles.newsSummaryItem}>
                            <MaterialIcons size={14} color={Colors.text1} name='library-books' />
                            <Text style={styles.newsSummaryText}> 3 min read</Text>
                        </View>
                        <View style={styles.newsSummaryItem}>
                        <FontAwesome5 name="user-alt" size={14} color={Colors.text1} />                            
                            <Text style={styles.newsSummaryText}> Jude-Bela</Text>
                        </View>
                        
                    </View>
                </View>
                <View>
                    <Text style={styles.articleWriteUp}>
                        The country has more in oil reserves than all but two other countries worldwide — that is equal to 13% of the global supply. But just about 50 years ago, Qatar’s economy was largely dependent on fishing, and one of the poorest in the world. So what happened? You’re about to find out the most incredible economic success story ever.

                        GDP may be the standard method for gauging the size of a particular country or region’s economy, but it does not account for all of the wealth generated by that nation. A more accurate indicator of a country’s economic output is its gross national income, or GNI.This measure captures all economic activity within a nation’s borders in addition to the wealth created by nationally-owned entities operating in other countries. With that said, Qatar’s GNI per capita equals a whooping $116,799. took a galley of type and scrambled it to make a type specimen book.

                        But how did a small country with population size of less than 3 million people living on a 12,000 sq km of land amass such wealth? The short answer to that is oil. But there are other small countries with oil not doing as well, take for example Kuwait. 

                        This brings us to the story of Qatar’s economy. Before the emergence of the petrol-based industry, Qatar was a poor pearl diving country. The exploration of oil and gas fields began in 1939. 

                        In 1973, oil production and revenues increased dramatically, moving Qatar out of the ranks of the world’s poorest countries and providing it with one of the highest per capita incomes in the world. But that is not the full story behind the transformation.

                        The primary sources of income for this tiny nation used to be its dwindling fishing industry, and extraction of pearls out of the ocean.
                    </Text>
                </View>
            </View>
        </ScrollView>
    )
}

export default ArticleRead;

const styles = StyleSheet.create({
    news: {
        flex: 1,
        paddingVertical: 16,
        paddingHorizontal: 20,            
        width: Dimensions.get('window').width,
    },
    imageContainer: {
        width: Dimensions.get('window').width,
        marginRight: 19
    },
    image: {
        height: 170,        
        resizeMode: 'contain'
    },
    crumbs: {
        borderBottomColor: '#cdcccc',
        paddingBottom: 24,
        borderBottomWidth: 0.5
    },
    crumbText: {
        fontFamily: 'DMRegular',
        fontWeight: '500'
    },
    newsTitle: {
        fontSize: 36,
        fontFamily: 'DMSerif',
        marginVertical: 3,        
        lineHeight: 50,
        letterSpacing: 0.36,
        color: '#000000',
        marginBottom: 15,
    },
    newsDetails: {
        flex: 1
    },
    newsCaption: {
        color: Colors.text2,
        fontSize: 14,
        fontFamily: 'DMRegular',
        marginBottom: 5,        
        fontWeight: '500',
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: -0.408,
        color: '#343A40'
    },
    newsSummary: {
        marginTop: 10,
        flexDirection: 'row',
        justifyContent: 'space-between'
    },
    newsSummaryText: {
        fontSize: 12,
        fontFamily: 'DMRegular',
        color: '#8E8D8D',
        lineHeight: 18
    },
    newsSummaryItem: {
        flexDirection: 'row',
        minWidth: 75,
        justifyContent: 'space-between'
    },
    articleCategoryContainer: {
        minWidth: 100,
        flexDirection: 'row',
        alignItems: 'center' ,
        marginTop: 24,
        marginBottom: 8,  
           
    },
    articleCategoryText: {
        fontSize: 12,  
    },
    articleWriteUp: {   
        marginTop: 24,     
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 30,
    letterSpacing: -0.408,
    color: '#343A40',
    marginBottom: 100
    }
});
